version: "3.5"

services:
  echoes-compress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name:  echoes-compress
    environment:
      # CRON
      CRON_SCHEDULE: '0 0 8 * * *'
    ports:
      - "4001:4000"

