version: "3.5"

services:
  echoes-backup-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name:  echoes-backup-client
    environment:
      # CRON
      CRON_SCHEDULE: '0 0 8 * * *'
    ports:
      - "4001:4000"

