#GNUPLOT command file automatically generated by Echoes %APP_VERSION on mié. sept. 2 00:06:12 2020 GMT
#set terminal X11 size 1024,768 font "fixed,10" 
set termoption noenhanced
set border 4095
set ytics out
set mxtics 10
set mytics 10
set mztics 10
set ztics out
set title "3D Spectrogram  UTC: 2/9/20 0:06 " offset 0,3
set xlabel "Hz" font "fixed,16" offset 0,-2
set ylabel "UTC Hour"  font "fixed,16"
set zlabel "dBfs" font "fixed,16" 
set key left outside
set grid xtics ytics ztics
set cblabel "dBfs" font "fixed,16" offset 1,0
set xtics out rotate border offset 0,-1 format "%.0f" 
unset surface

set view 45,45, 1,1
set pm3d implicit at s

set format y "%H:%M:%S" timedate
set palette model RGB
set cbrange [-150:50]
set palette defined (-130 "#000000", -122 "#0000ff", -114 "#800080", -106 "#ffa500", -98 "#ffff00", -90 "#ffffff", 50 "#ffffff")
print "plotting shot 1 of 343
set title "Spectrogram  UTC: 3/9/20 0:00 file: spec3D_Fuenlabrada_automatic_2020-09-02_00001.dat " offset 0,3
splot "spec3D_Fuenlabrada_automatic_2020-09-02_00001.dat" using 2:1:3 notitle
pause -1 "hit return to continue" 
print "plotting shot 2 of 343